"""Run transparent data-quality and fact reconciliation checks."""
from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CHECKS = [
    ("Duplicate order primary keys", "SELECT COUNT(*) FROM (SELECT order_id FROM raw_orders GROUP BY order_id HAVING COUNT(*) > 1)"),
    ("Null customer IDs", "SELECT COUNT(*) FROM raw_orders WHERE customer_id IS NULL OR TRIM(customer_id) = ''"),
    ("Null purchase timestamps", "SELECT COUNT(*) FROM raw_orders WHERE order_purchase_timestamp IS NULL OR TRIM(order_purchase_timestamp) = ''"),
    ("Invalid order statuses", "SELECT COUNT(*) FROM raw_orders WHERE order_status NOT IN ('created','approved','invoiced','processing','shipped','delivered','unavailable','canceled')"),
    ("Negative item prices", "SELECT COUNT(*) FROM raw_order_items WHERE CAST(price AS REAL) < 0"),
    ("Zero or negative item quantities", "SELECT COUNT(*) FROM raw_order_items WHERE CAST(order_item_id AS INTEGER) <= 0"),
    ("Missing category translations", "SELECT COUNT(*) FROM raw_products p LEFT JOIN raw_category_translation t ON p.product_category_name = t.product_category_name WHERE p.product_category_name IS NOT NULL AND t.product_category_name IS NULL"),
    ("Missing review scores", "SELECT COUNT(*) FROM raw_reviews WHERE review_score IS NULL OR TRIM(review_score) = ''"),
    ("Delivered before purchase", "SELECT COUNT(*) FROM raw_orders WHERE order_delivered_customer_date < order_purchase_timestamp"),
    ("Delivered before carrier handoff", "SELECT COUNT(*) FROM raw_orders WHERE order_delivered_customer_date < order_delivered_carrier_date"),
    ("Estimated delivery before purchase", "SELECT COUNT(*) FROM raw_orders WHERE order_estimated_delivery_date < order_purchase_timestamp"),
    ("Duplicate payment keys", "SELECT COUNT(*) FROM (SELECT order_id, payment_sequential FROM raw_payments GROUP BY 1,2 HAVING COUNT(*) > 1)"),
]
RECONCILIATIONS = [
    ("Orders", "SELECT COUNT(*) FROM raw_orders", "SELECT COUNT(*) FROM fact_orders"),
    ("Order items", "SELECT COUNT(*) FROM raw_order_items", "SELECT COUNT(*) FROM fact_order_items"),
    ("Item revenue", "SELECT ROUND(SUM(CAST(price AS REAL)), 2) FROM raw_order_items", "SELECT ROUND(SUM(item_revenue), 2) FROM fact_order_items"),
    ("Freight", "SELECT ROUND(SUM(CAST(freight_value AS REAL)), 2) FROM raw_order_items", "SELECT ROUND(SUM(freight_cost), 2) FROM fact_order_items"),
    ("Payment value", "SELECT ROUND(SUM(CAST(payment_value AS REAL)), 2) FROM raw_payments", "SELECT ROUND(SUM(payment_value), 2) FROM fact_payments"),
]


def scalar(connection: sqlite3.Connection, query: str):
    return connection.execute(query).fetchone()[0]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", type=Path, default=ROOT / "data" / "olist_analytics.sqlite")
    parser.add_argument("--report", type=Path, default=ROOT / "reports" / "data_quality_summary.md")
    args = parser.parse_args()
    with sqlite3.connect(args.database) as connection:
        quality = [(name, scalar(connection, query)) for name, query in CHECKS]
        reconciliation = [(name, scalar(connection, source), scalar(connection, model)) for name, source, model in RECONCILIATIONS]
    args.report.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Data Quality Summary", "", "Generated by `src/validate_data.py`. Raw records are preserved; this report flags exceptions rather than deleting them.", "", "## Quality checks", "", "| Check | Exceptions |", "|---|---:|"]
    lines += [f"| {name} | {value:,} |" for name, value in quality]
    lines += ["", "## Reconciliation", "", "| Metric | Raw source | Analytical fact | Result |", "|---|---:|---:|---|"]
    failures = []
    for name, source, model in reconciliation:
        ok = source == model
        lines.append(f"| {name} | {source:,} | {model:,} | {'PASS' if ok else 'FAIL'} |")
        if not ok:
            failures.append(name)
    lines += ["", "## Filtering rules", "", "No raw rows are deleted. KPIs requiring delivery performance include delivered orders with both purchase and delivery timestamps. Review metrics use one deterministic latest review per order in `fact_reviews`; raw review rows remain available."]
    args.report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.report}")
    if failures:
        raise SystemExit("Reconciliation failed: " + ", ".join(failures))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
